compile:
	@echo "Compiling classes..."
	@javac *.java
	@javac sdle/crdt/*.java
	@javac sdle/serverClient/*.java
	@javac sdle/shopping/list/*.java

compileCRDT:
	@echo "Compiling CRDT classes..."
	@javac *.java
	@javac sdle/crdt/*.java

compileServerClient:
	@echo "Compiling ServerClient classes..."
	@javac *.java
	@javac sdle/serverClient/*.java

compileShopping:
	@echo "Compiling Shopping classes..."
	@javac *.java
	@javac sdle/shopping/list/*.java

clean:
	@echo "Cleaning..."
	@rm -f *.class
	@rm -f sdle/crdt/*.class
	@rm -f sdle/serverClient/*.class
	@rm -f sdle/shopping/*.class


