compile:
	@echo "Compiling classes..."
	@javac *.java
	@javac crdts/*.java
	@javac utils/*.java
	@javac backend/*.java
	@javac shopping/*.java

compileCRDT:
	@echo "Compiling CRDT classes..."
	@javac *.java
	@javac crdts/*.java

compileBackend:
	@echo "Compiling ServerClient classes..."
	@javac *.java
	@javac backend/*.java

compileShopping:
	@echo "Compiling Shopping classes..."
	@javac *.java
	@javac /shopping/*.java

clean:
	@echo "Cleaning..."
	@rm -f *.class
	@rm -f crdts/*.class
	@rm -f utils/*.class
	@rm -f backend/*.class
	@rm -f shopping/*.class
