compile:
	@echo "Compiling classes..."
	@javac *.java
	@javac crdts/*.java
	@javac utils/*.java
	@javac backend/*.java
	@javac backend/server1/*.java
	@javac backend/server2/*.java
	@javac backend/server3/*.java
	@javac backend/server4/*.java
	@javac shopping/*.java
	@javac client/client1/*.java
	@javac client/client2/*.java



clean:
	@echo "Cleaning..."
	@rm -f *.class
	@rm -f crdts/*.class
	@rm -f utils/*.class
	@rm -f backend/*.class
	@rm -f shopping/*.class
